#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#Key-value

info = {
    'stu1101' : "TengLan Wu"  ,
    'stu1102' : "LongZe Luola" ,
    'stu1103' : "XiaoZe Maliya",
}

'''print(info)
#print(info["stu1101"])
info["stu1101"] ="武藤兰"      #修改
info["stu1104"] ="闯进空"      #新增
print(info)

#del
#del info["stu1101"]    #指定删除
#info.pop("stu1101")    #指定删除
#info.popitem()         #随机删除
print(info)

#info['stu1104']         #查找不存在
print(info.get('stu1104'))    #查找不存在，有就显示，没有就None
print('stu1103' in info)      #同上

info.values()   #打印出所有的值
info.keys()     #将所有的key打印出来
info.setdefault("1",{2:[3,4]})  #新增一个  重复的先取值
'''
'''info2 = {
    'stu1101' : "Xi Hong Shi",
    2:3,
    4:5,
}

info.update(info2)
print(info)         #合并两个字典，相同的更新，不同的新增
print(info.items())  #将字典合并成列表

info3 = dict.fromkeys([6,7,8],[1,{"name":"wu hua guo"},666])    #初始化一个新的字典
print(info3)
info3[7][1]['name'] = "名字"    #全部更新，  多层结构会全部更新 
'''

for i in info:
    print(i,info[i])                 #循环打印

for k,v in info.items():
    print(k,v)                      #循环打印
